# Generated by Django 3.1.3 on 2020-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accused_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accused',
            name='first_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='accused',
            name='last_name',
            field=models.CharField(max_length=70),
        ),
    ]
