# Generated by Django 3.1.3 on 2020-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accused_app', '0003_auto_20201114_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='accused',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
