# Generated by Django 3.1.3 on 2020-11-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accused_app', '0004_accused_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accused',
            name='arrest_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='accused',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='accused_app.accused'),
        ),
    ]
