# Generated by Django 3.1.3 on 2020-11-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accused_app', '0005_auto_20201118_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accused',
            name='arrest_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accused',
            name='birth_city',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
