# Generated by Django 3.1.3 on 2020-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('nation_code', models.IntegerField(unique=True)),
                ('responsibility', models.CharField(max_length=500, null=True)),
                ('type_team', models.CharField(max_length=500, null=True)),
                ('birthday', models.DateField(null=True)),
                ('father_name', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(default='مشهد', max_length=500, null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('subscription_type', models.CharField(choices=[('n', 'normal'), ('a', 'active')], default='normal', max_length=10)),
                ('province_corp', models.CharField(default='سپاه امام رضا', max_length=500)),
                ('area', models.CharField(default='یاسر', max_length=500)),
                ('realm', models.CharField(default='حوزه یک', max_length=500)),
                ('base', models.CharField(max_length=500, null=True)),
                ('equipment', models.CharField(default='تونفا', max_length=500)),
                ('serial_equipment', models.CharField(default='1', max_length=500)),
            ],
        ),
    ]
