# Generated by Django 3.1.3 on 2020-11-24 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0002_auto_20201114_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='register_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='nation_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_type',
            field=models.CharField(choices=[('normal', 'عادی'), ('active', 'فعال')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='type_team',
            field=models.CharField(choices=[('base', 'پایگاه'), ('support', 'پشتیبانی')], default='base', max_length=500, null=True),
        ),
    ]
