# Generated by Django 3.1.3 on 2020-11-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patrol',
            table='report_patrols',
        ),
    ]
