# Generated by Django 3.1.3 on 2020-11-18 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_auto_20201118_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='time_ended_at',
            field=models.TimeField(default=datetime.datetime(2020, 11, 19, 3, 18, 54, 638137, tzinfo=utc)),
        ),
    ]
