# Generated by Django 3.1.3 on 2020-11-24 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_auto_20201118_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='time_ended_at',
            field=models.TimeField(default=datetime.datetime(2020, 11, 24, 23, 53, 14, 978456, tzinfo=utc), null=True),
        ),
    ]
